#######DEPLOYMENT.YAML#########
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default          # <-- added
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: flask
        image: devoopsguru/hello-world:20260429111554

        ports:
        - containerPort: 5000




---



##########SERVICE.YAML#########
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default          # <-- added
  labels:
    app: hello-world
    release: prometheus
spec:
  selector:
    app: hello-world
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP


  #run the file "kubectl -f ./deployment.yaml"

  # kubectl get all

  # port forwording : kubectl port-forward svc/hello-world-service 8080:80